### ISSUE TITLE
Playing video from Favorites does not show valid image and info

### ISSUE THREAD

**Issue by vlna** [lama18/plugin.video.televizeseznam.cz#16]
Function 
https://github.com/wombat01/plugin.video.televizeseznam.cz/blob/737833366b00480d4e444b5d2cb3970a67074db0/resources/lib/plugin.py#L264 should refresh image and info.

Reproduce issue:
1. Add any video available in addon to Favorites
2. Go to Favorites and click to video
3. Press 'i' to show information

**Comment by wombat01** [comment]
Fix via https://github.com/wombat01/plugin.video.televizeseznam.cz/commit/195a297c2db257525f0ef50f7d4b374dd5d40b34
