### ISSUE TITLE
Addon returns to search form after playing video from search list

### ISSUE THREAD

**Issue by vlna** [lama18/plugin.video.televizeseznam.cz#17]
Expected behaviour: After playing video from search list addon displays search list and not the search form again

Reproduce issue:
- Go to the search form and type search string (e.g. ```trai```)
- Select any top level video and play it
- You can jump closer to the end of the video
- When the video ends, the video search form appears again

**Comment by wombat01** [comment]
Fix via https://github.com/wombat01/plugin.video.televizeseznam.cz/commit/195a297c2db257525f0ef50f7d4b374dd5d40b34
