### ISSUE TITLE
Rozpravky nejdu prehrat

### ISSUE THREAD

**Issue by ghost** [lama18/plugin.video.televizeseznam.cz#6]
Prehravanie videi v sekcii rozpravky zlyha. V logu vidim chybu "ERROR: CCurlFile::Open failed with code 403"
Skusal som to napriklad na URL https://www.televizeseznam.cz/video/krtek/krtek-a-hodiny-227457 ktora mi cez browser ide prehrat bez problemov

**Comment by rywko** [comment]
Ospravedlnujem sa za chybu na mojej strane. Doplnok som mal nainstalovany zo stareho repozitara. Po instalacii najnovsej verzie z novejo repa prehravanie funguje
